FROM node:18-alpine3.19 AS builder

WORKDIR /app
COPY web/package*.json ./
COPY web/tsconfig.json ./
COPY web/vite.config.ts ./
COPY web/tailwind.config.js ./
COPY web/postcss.config.js ./
COPY web/env.d.ts ./
COPY web/manager/public/ ./public/
RUN npm ci && npm cache clean --force

ARG VITE_API_URL=/api
ENV VITE_API_URL=$VITE_API_URL
ARG VITE_BUILD_VERSION=development
ENV VITE_BUILD_VERSION=$VITE_BUILD_VERSION

COPY web/manager/ ./manager/
COPY web/landing/ ./landing/
COPY web/shared/ ./shared/
RUN npm run build:manager

FROM nginx:alpine
RUN rm -f /etc/nginx/conf.d/default.conf
COPY nginx/nginx.front.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist-manager /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
