<template>
  <div class="min-h-screen bg-gray-50 text-gray-900 transition-colors duration-200 dark:bg-gray-900 dark:text-gray-100">
    <PublicHeader active="docs" />

    <main class="w-full px-4 py-8 pb-24 sm:px-6 lg:px-10 lg:py-10 xl:px-12">
      <section class="grid gap-8 py-8 sm:py-12 lg:grid-cols-[1.1fr_.9fr] lg:items-end lg:gap-16 lg:py-16" aria-labelledby="docs-title">
        <div><div class="mb-4 inline-flex items-center gap-2 rounded-full bg-primary-100 px-3 py-1 text-xs font-semibold text-primary-700 dark:bg-primary-900 dark:text-primary-300"><span class="h-2 w-2 rounded-full bg-primary-600" />Guia do administrador</div><h1 id="docs-title" class="max-w-3xl text-4xl font-bold tracking-tight sm:text-5xl lg:text-6xl">Seu cofre, seu host.</h1><p class="mt-5 max-w-2xl text-lg leading-8 text-gray-600 dark:text-gray-300">Instale, configure e atualize o Atacte com o mesmo cuidado que você dedica aos seus dados.</p></div>
        <div class="rounded-lg border border-gray-200 bg-white p-5 shadow-sm dark:border-gray-700 dark:bg-gray-800"><div class="flex items-center gap-3"><div class="flex h-10 w-10 items-center justify-center rounded-lg bg-primary-100 dark:bg-primary-900"><BookOpenIcon class="h-5 w-5 text-primary-600 dark:text-primary-400" /></div><div><p class="font-semibold">Documentação rápida</p><p class="text-sm text-gray-500 dark:text-gray-400">Instalação, operação e segurança.</p></div></div><div class="mt-5 grid grid-cols-3 gap-2 text-center text-xs"><a href="#instalacao" class="rounded-lg bg-gray-50 px-2 py-3 font-medium text-gray-700 hover:bg-gray-100 dark:bg-gray-700 dark:text-gray-200 dark:hover:bg-gray-600">Instalar</a><a href="#atualizacao" class="rounded-lg bg-gray-50 px-2 py-3 font-medium text-gray-700 hover:bg-gray-100 dark:bg-gray-700 dark:text-gray-200 dark:hover:bg-gray-600">Atualizar</a><a href="#seguranca" class="rounded-lg bg-gray-50 px-2 py-3 font-medium text-gray-700 hover:bg-gray-100 dark:bg-gray-700 dark:text-gray-200 dark:hover:bg-gray-600">Proteger</a></div></div>
      </section>

      <section id="requisitos" class="border-t border-gray-200 py-12 dark:border-gray-700 sm:py-16"><div class="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><div><p class="text-sm font-semibold text-primary-600 dark:text-primary-400">01 · Antes de começar</p><h2 class="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">Requisitos simples.</h2></div><div class="grid gap-3 sm:grid-cols-3"><article v-for="item in requirements" :key="item.title" class="rounded-lg border border-gray-200 bg-white p-5 shadow-sm dark:border-gray-700 dark:bg-gray-800"><component :is="item.icon" class="h-5 w-5 text-primary-600 dark:text-primary-400" /><h3 class="mt-4 font-semibold">{{ item.title }}</h3><p class="mt-2 text-sm leading-6 text-gray-500 dark:text-gray-400">{{ item.description }}</p></article></div></div></section>

      <section id="instalacao" class="border-t border-gray-200 py-12 dark:border-gray-700 sm:py-16"><p class="text-sm font-semibold text-primary-600 dark:text-primary-400">02 · Instalação</p><div class="mt-2 grid gap-6 lg:grid-cols-[.7fr_1.3fr] lg:items-start"><div><h2 class="text-3xl font-bold tracking-tight sm:text-4xl">Um comando.</h2><p class="mt-4 leading-7 text-gray-600 dark:text-gray-400">O instalador cria a configuração inicial, baixa as imagens e preserva o volume PostgreSQL.</p></div><div><pre class="overflow-x-auto rounded-lg border border-gray-700 bg-gray-950 px-5 py-4 font-mono text-sm leading-7 text-green-300 shadow-inner dark:border-gray-600 dark:bg-black dark:text-green-200"><code>curl -fsSL https://atacte.vercel.app/install.sh | sh</code></pre><p class="mt-4 text-sm leading-6 text-gray-600 dark:text-gray-400">Acesse <code class="font-mono text-primary-700 dark:text-primary-300">http://localhost:3456</code> e crie a primeira conta. Para fixar uma versão, use <code class="font-mono text-primary-700 dark:text-primary-300">ATACTE_RELEASE_REF=v1.2.3</code> antes do comando.</p></div></div></section>

      <section id="atualizacao" class="border-t border-gray-200 py-12 dark:border-gray-700 sm:py-16"><p class="text-sm font-semibold text-primary-600 dark:text-primary-400">03 · Atualização</p><div class="mt-2 grid gap-6 lg:grid-cols-[.7fr_1.3fr]"><div><h2 class="text-3xl font-bold tracking-tight sm:text-4xl">Atualize com migrations versionadas.</h2><p class="mt-4 leading-7 text-gray-600 dark:text-gray-400">O updater pode ser acionado pelo aviso no manager ou pelo host. Antes de substituir o backend, ele executa as migrations do Prisma incluídas na imagem.</p></div><div><pre class="overflow-x-auto rounded-lg border border-gray-700 bg-gray-950 px-5 py-4 font-mono text-sm leading-7 text-green-300 shadow-inner dark:border-gray-600 dark:bg-black dark:text-green-200"><code>cd ~/.atacte
docker compose pull backend front updater
docker compose up -d --no-build --remove-orphans</code></pre><p class="mt-4 text-sm leading-6 text-gray-600 dark:text-gray-400">Valide com <code class="font-mono text-primary-700 dark:text-primary-300">curl -fsS http://localhost:3457/health</code>. As migrations não removem volumes; faça backup antes de atualizar.</p></div></div></section>

      <section id="backup" class="border-t border-gray-200 py-12 dark:border-gray-700 sm:py-16"><p class="text-sm font-semibold text-primary-600 dark:text-primary-400">04 · Continuidade</p><div class="mt-2 grid gap-6 lg:grid-cols-[.7fr_1.3fr]"><div><h2 class="text-3xl font-bold tracking-tight sm:text-4xl">Faça backup antes de mudar.</h2><p class="mt-4 leading-7 text-gray-600 dark:text-gray-400">Um dump lógico facilita testar restaurações e migrar para outro host.</p></div><pre class="overflow-x-auto rounded-lg border border-gray-700 bg-gray-950 px-5 py-4 font-mono text-sm leading-7 text-green-300 shadow-inner dark:border-gray-600 dark:bg-black dark:text-green-200"><code>cd ~/.atacte
docker compose exec -T postgres pg_dump -U atacte -d atacte > atacte-backup.sql</code></pre></div></section>

      <section id="seguranca" class="border-t border-gray-200 py-12 dark:border-gray-700 sm:py-16"><p class="text-sm font-semibold text-primary-600 dark:text-primary-400">05 · Segurança</p><div class="mt-2 grid gap-6 lg:grid-cols-[.7fr_1.3fr]"><div><h2 class="text-3xl font-bold tracking-tight sm:text-4xl">Proteção operacional.</h2></div><div class="rounded-lg border border-green-200 bg-green-50 p-5 dark:border-green-900 dark:bg-green-950"><div class="flex gap-3"><ShieldCheckIcon class="h-5 w-5 shrink-0 text-primary-600 dark:text-primary-400" /><p class="text-sm leading-7 text-gray-700 dark:text-gray-300">Use HTTPS, não exponha PostgreSQL ou o updater e faça backups criptografados. As sessões usam cookies HttpOnly e CSRF. Mantenha os segredos do servidor fora do repositório.</p></div></div></div></section>
    </main>

    <footer class="border-t border-gray-200 dark:border-gray-700"><div class="flex w-full flex-col gap-3 px-4 py-6 text-sm text-gray-500 dark:text-gray-400 sm:flex-row sm:items-center sm:justify-between sm:px-6 lg:px-10 xl:px-12"><div class="flex flex-wrap items-center gap-x-2 gap-y-1"><PublicLogo :size="24" /><span>Atacte · seu cofre, suas regras.</span><span aria-label="Direitos autorais">© 2026 Fernando Forastieri · Licença MIT</span></div><nav class="flex items-center gap-4" aria-label="Links do rodapé"><a class="hover:text-primary-600 dark:hover:text-primary-400" href="/">Início</a><a class="hover:text-primary-600 dark:hover:text-primary-400" href="/releases/">Releases</a><a class="hover:text-primary-600 dark:hover:text-primary-400" href="https://github.com/ferforastieri/atacte" rel="noreferrer">GitHub</a></nav></div></footer>
  </div>
</template>

<script setup lang="ts">
import PublicHeader from '../PublicHeader.vue'
import PublicLogo from '../PublicLogo.vue'
import { BookOpenIcon, CloudIcon, LockClosedIcon, ServerIcon, ShieldCheckIcon } from '@heroicons/vue/24/outline'
const requirements = [
  { title: 'Docker', description: 'Engine e Compose v2 em Linux ou macOS.', icon: CloudIcon },
  { title: 'HTTPS', description: 'Domínio, VPN ou reverse proxy para acesso remoto.', icon: LockClosedIcon },
  { title: 'Recursos', description: 'Pelo menos 1 GB de RAM para começar.', icon: ServerIcon }
]
</script>
