<template>
  <div class="min-h-screen bg-gray-50 text-gray-900 dark:bg-gray-900 dark:text-gray-100">
    <header class="mx-auto flex h-16 max-w-[1200px] items-center justify-between border-b border-gray-200 bg-white px-4 shadow-sm transition-colors dark:border-gray-700 dark:bg-gray-800 sm:px-6">
      <a class="flex items-center gap-2 font-bold" href="/"><img class="h-8 w-8 rounded-lg" src="/favicon-web.png" alt="" />Atacte</a>
      <nav class="flex items-center gap-1 text-sm font-medium text-gray-700 dark:text-gray-300"><a class="rounded-lg px-3 py-2 hover:bg-gray-100 dark:hover:bg-gray-700" href="/docs/">Documentação</a><a class="rounded-lg px-3 py-2 hover:bg-gray-100 dark:hover:bg-gray-700" href="/releases/">Releases</a><a class="rounded-lg bg-primary-600 px-4 py-2 text-white hover:bg-primary-700" :href="managerUrl">Abrir gerenciador ↗</a></nav>
    </header>
    <main class="mx-auto max-w-[920px] px-4 py-20 sm:px-6">
      <div class="max-w-3xl pb-11"><p class="text-xs font-semibold uppercase tracking-wider text-primary-700 dark:text-primary-300"><span class="mr-2 inline-block h-2 w-2 rounded-full bg-primary-600 align-middle" /> Documentação / self-hosted</p><h1 class="mt-5 text-5xl font-extrabold leading-none tracking-[-.06em] sm:text-7xl">Seu cofre, seu host.</h1><p class="mt-6 text-lg leading-7 text-gray-500 dark:text-gray-400">Instale, configure e atualize o Atacte sem migrações automáticas ou serviços externos obrigatórios.</p></div>
      <section id="requisitos" class="border-t border-gray-200 py-14 dark:border-gray-700"><p class="text-xs font-semibold uppercase tracking-wider text-primary-700 dark:text-primary-300">01 / REQUISITOS</p><h2 class="mt-4 text-4xl font-extrabold tracking-[-.05em] sm:text-5xl">Antes de começar.</h2><ul class="mt-5 list-disc space-y-2 pl-5 leading-7 text-gray-600 dark:text-gray-300"><li>Docker Engine 24+ e Docker Compose v2.</li><li>Um host Linux ou macOS com pelo menos 1 GB de RAM.</li><li>Um domínio ou VPN para acesso remoto via HTTPS.</li></ul></section>
      <section id="instalacao" class="border-t border-gray-200 py-14 dark:border-gray-700"><p class="text-xs font-semibold uppercase tracking-wider text-primary-700 dark:text-primary-300">02 / INSTALAÇÃO</p><h2 class="mt-4 text-4xl font-extrabold tracking-[-.05em] sm:text-5xl">Um comando.</h2><p class="mt-5 leading-7 text-gray-600 dark:text-gray-300">O instalador baixa o Compose e o updater, cria um diretório privado e preserva o volume PostgreSQL.</p><pre class="mt-6 overflow-auto rounded-lg border border-gray-700 bg-gray-900 px-5 py-4 font-mono text-sm leading-7 text-green-200"><code>curl -fsSL https://atacte.vercel.app/install.sh | sh</code></pre><p class="leading-7 text-gray-600 dark:text-gray-300">Para usar uma versão específica: <code class="font-mono text-sm text-primary-700 dark:text-primary-300">ATACTE_RELEASE_REF=v1.2.3 curl -fsSL https://atacte.vercel.app/install.sh | sh</code>.</p><p class="mt-4 leading-7 text-gray-600 dark:text-gray-300">Também é possível baixar <a class="text-primary-700 underline underline-offset-4 dark:text-primary-300" href="https://github.com/ferforastieri/atacte/releases">Compose e imagens pelas releases</a> e executar <code class="font-mono text-sm text-primary-700 dark:text-primary-300">docker compose up -d</code> dentro de <code class="font-mono text-sm text-primary-700 dark:text-primary-300">~/.atacte</code>.</p></section>
      <section id="atualizacao" class="border-t border-gray-200 py-14 dark:border-gray-700"><p class="text-xs font-semibold uppercase tracking-wider text-primary-700 dark:text-primary-300">03 / ATUALIZAÇÃO</p><h2 class="mt-4 text-4xl font-extrabold tracking-[-.05em] sm:text-5xl">Atualiza sem tocar no banco.</h2><p class="mt-5 leading-7 text-gray-600 dark:text-gray-300">O manager consulta a versão publicada. Administradores recebem um aviso e podem iniciar o updater; ele faz pull das imagens e recria backend/frontend sem executar Prisma migrate, db push ou apagar volumes.</p><pre class="mt-6 overflow-auto rounded-lg border border-gray-700 bg-gray-900 px-5 py-4 font-mono text-sm leading-7 text-green-200"><code>cd ~/.atacte
docker compose pull backend front
docker compose up -d --no-build --remove-orphans backend front</code></pre><p class="leading-7 text-gray-600 dark:text-gray-300">Se a atualização falhar, volte para a tag SHA anterior no Compose e valide <code class="font-mono text-sm text-primary-700 dark:text-primary-300">curl http://localhost:3457/health</code>.</p></section>
      <section id="seguranca" class="border-t border-gray-200 py-14 dark:border-gray-700"><p class="text-xs font-semibold uppercase tracking-wider text-primary-700 dark:text-primary-300">04 / SEGURANÇA</p><h2 class="mt-4 text-4xl font-extrabold tracking-[-.05em] sm:text-5xl">Transparência primeiro.</h2><p class="mt-5 leading-7 text-gray-600 dark:text-gray-300">A sessão usa cookie HttpOnly e proteção CSRF. Mantenha o Atacte atrás de HTTPS, não exponha PostgreSQL, limite o painel à sua rede/VPN e faça backup do volume.</p><div class="mt-6 rounded-r-lg border-l-4 border-primary-600 bg-green-50 p-5 dark:bg-green-950"><strong class="text-xs font-semibold uppercase tracking-wider text-primary-700 dark:text-primary-300">Risco conhecido</strong><p class="mt-2 mb-0 leading-7 text-gray-600 dark:text-gray-300">A chave de cifragem atual deriva do email (SHA-256) e permanece armazenada no banco por compatibilidade. Isso não é zero-knowledge; trate o PostgreSQL como dado altamente sensível.</p></div></section>
    </main>
    <footer class="mx-auto flex max-w-[1200px] justify-between border-t border-gray-200 px-4 py-6 text-xs text-gray-500 dark:border-gray-700 dark:text-gray-400 sm:px-6"><span>Atacte / private vault</span><span><a class="text-primary-700 dark:text-primary-300" href="/">Início</a> · <a class="text-primary-700 dark:text-primary-300" href="/releases/">Releases</a> · Self-hosted</span></footer>
  </div>
</template>

<script setup lang="ts">
const managerUrl = import.meta.env.VITE_MANAGER_URL || '/manager/'
</script>
